### ISSUE TITLE
It's broken

### ISSUE THREAD

**Issue by RetroGameTalk** [rari-teh/tailconcerto#2]
Very early in game after first cutscene it goes to a black screen and you hear a voice track looping.
I tried all 3 versions of the patch all did the same.

**Comment by Kobun42** [comment]
Exact same stuff I've faced for a long time. Both pre-patched copies and applying the patch manually with my own copy of the game yield the same result, all emulators, even the PS3's PS1 emulator fares no better.

Wonder if it'll ever be fixed.

**Comment by rari-teh** [comment]
What if I told you I’ve been sitting on a version 2 that fixes the in-game sound effects and is worlds less hacky and prone to breaking but I’ve been too lazy to write the readme and documentation

Anyway, maybe this is the push I needed. Stay tuned

**Comment by rari-teh** [comment]
[It is done.](http://rarit.ee/patches.htm#tc)

Any feedback would be appreciated :)

**Comment by RetroGameTalk** [comment]
Great thanks!
